### ISSUE TITLE
Option 7 location search fails for me in sample application.

### ISSUE THREAD

**Issue by andrewjtimmons** [Instagram/instagram-ruby-gem#111]
1.  Go to https://github.com/Instagram/instagram-ruby-gem/
2.  Copy the "Sample Application" to a .rb file
3.  Start the application in terminal.  
4.  Go to http://localhost:4567/
5.  Connect to instagram
6.  Click option 7 for location based search

Get error:
NoMethodError at /location_search
undefined method `each' for nil:NilClass
file: instragram.rb location: block in <main> line: 115

Gist of cmd line sinatra server output
https://gist.github.com/andrewjtimmons/52948c38e53ac17c97dc

Options 1-6 and 8,9 work at http://localhost:4567/nav

**Comment by DylanDavidson** [comment]
As mentioned above, this can be solved by using the latest version of the gem from Github like so:
```ruby
gem 'instagram', github: 'instagram/instagram-ruby-gem'
```

Therefore, this issue should be closed.

**Comment by andrewjtimmons** [comment]
Thank you!
