### ISSUE TITLE
Instagram.validate_update expects sha1= to be in X-Hub-Signature header, but it isn't.

### ISSUE THREAD

**Issue by sealabcore** [Instagram/instagram-ruby-gem#130]
https://github.com/Instagram/instagram-ruby-gem/blob/master/lib/instagram/client/subscriptions.rb#L147 

Splits the array on "sha1=" but there is no sha1= in the header value.

![screenshot 2014-08-29 13 47 56](https://cloud.githubusercontent.com/assets/79464/4096173/d5025d2a-2fbd-11e4-8d08-e5aa498f71c0.png)

**Comment by DylanDavidson** [comment]
This was taken care of by #131, the issue should be closed.

**Comment by sealabcore** [comment]
"This was taken care of by #131, the issue should be closed."

Closing issue.
