### ISSUE TITLE
Better Error Messaging for Instagram::BadRequest 

### ISSUE THREAD

**Issue by trafnar** [Instagram/instagram-ruby-gem#22]
Enhancement Suggestion:

I had some problems when using get_access_token that resulted in an Instagram::BadRequest exception. It was difficult to debug because the actual error messages from Instagram aren't shown.

The [error_message](https://github.com/Instagram/instagram-ruby-gem/blob/master/lib/faraday/raise_http_4xx.rb#L25) method could be altered to display instagram's response along the lines of "this request is missing a client_id".

**Comment by DylanDavidson** [comment]
It seems this was taken care of by #117, this issue should be closed.
